name: build
on:
  workflow_dispatch:
    inputs:
      MANIFEST:
        description: 'Manifest URL with -b branch'
        required: true
        default: 'https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-9.0'
      DT_LINK:
        description: 'DT Link with -b branch'
      REC_NAME:
        required: true
        default: 'pbrp'

env:
  MANIFEST: ${{ github.event.inputs.MANIFEST }}
  DT_LINK: ${{ github.event.inputs.DT_LINK }}
  REC_NAME: ${{ github.event.inputs.REC_NAME }}
  VENDOR: "xiaomi"
  CODENAME: "pine"
  FLAVOR: "eng"
  TZ: "Asia/Jakarta"

jobs:
  rec-ci:
    runs-on: ubuntu-20.04
    steps:
       - uses: rokibhasansagar/slimhub_actions@main
       - uses: PitchBlackRecoveryProject/Recovery-Compiler@production   
       - run: ghr -n ${REC_NAME}-$(date '+%Y%m%d')-pine v$(date '+%Y%m%d') out/target/product/pine/*pine*
